### PR TITLE
hypervisor: Disable TSO/UFO/CSUM offloads on virtio-net TAPs

### LINKED ISSUE #103: [Bug Report] can not access internet in sandbox
Image

### PR DESCRIPTION
**Pull request by chenhengqi**
Stop advertising VIRTIO_NET_F_{CSUM,GUEST_CSUM,*_TSO4,*_TSO6,*_UFO, *_ECN,CTRL_GUEST_OFFLOADS} so the guest computes full checksums and segments its own packets. This avoids CHECKSUM_PARTIAL packets reaching host NIC (which may disable tx-checksumming).

See internal commit 9e0a1d495b734cb1e883c3b9876a9aac22f91e6e and #103 for more context.

Closes #103.

### CODE REVIEW

File: hypervisor/virtio-devices/src/net.rs [hunk 1]
```diff
@@ -456,20 +456,8 @@ impl Net {
...
-                | 1 << VIRTIO_NET_F_GUEST_UFO
-                | 1 << VIRTIO_NET_F_HOST_ECN
-                | 1 << VIRTIO_NET_F_HOST_TSO4
-                | 1 << VIRTIO_NET_F_HOST_TSO6
-                | 1 << VIRTIO_NET_F_HOST_UFO
-                | 1 << VIRTIO_NET_F_MTU
-                | 1 << VIRTIO_RING_F_EVENT_IDX
-                | 1 << VIRTIO_F_VERSION_1;
+            let mut avail_features =
+                1 << VIRTIO_NET_F_MTU | 1 << VIRTIO_RING_F_EVENT_IDX | 1 << VIRTIO_F_VERSION_1;
```
[the remark this answers is not in the document]
Comment (chenhengqi) [reply hypervisor/virtio-devices/src/net.rs:460]: We don't use vhost-user net devices.

File: hypervisor/virtio-devices/src/net.rs [hunk 2]
```diff
@@ -456,20 +456,8 @@ impl Net {
...
-                | 1 << VIRTIO_NET_F_GUEST_TSO6
-                | 1 << VIRTIO_NET_F_GUEST_UFO
-                | 1 << VIRTIO_NET_F_HOST_ECN
-                | 1 << VIRTIO_NET_F_HOST_TSO4
-                | 1 << VIRTIO_NET_F_HOST_TSO6
-                | 1 << VIRTIO_NET_F_HOST_UFO
-                | 1 << VIRTIO_NET_F_MTU
-                | 1 << VIRTIO_RING_F_EVENT_IDX
-                | 1 << VIRTIO_F_VERSION_1;
+            let mut avail_features =
```
Comment (up2wing) [inline hypervisor/virtio-devices/src/net.rs:459]: Do we need some configuration to toggle the offload feature?

Comment (fslongjin) [reply hypervisor/virtio-devices/src/net.rs:459]: Seems no need~

Comment (chenhengqi) [reply hypervisor/virtio-devices/src/net.rs:459]: These features has to be always disabled because we can't handle csum in BPF code.

Comment (lisongqian) [reply hypervisor/virtio-devices/src/net.rs:459]: FYI, the patch of upstream: https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5029

Comment (chenhengqi) [reply hypervisor/virtio-devices/src/net.rs:459]: I am not aware of this upstream change but I mentioned the same change in commit message.
